project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    # - Notes/00-Welcome_to_the_Course.qmd
    - Notes/01-What_is_Data_Science.qmd
    - Notes/02-Workflows_Git_GitHub_Basics_Landing.qmd
    - Notes/03-Git_GitHub_Practice.qmd
    - Notes/04-R_Basics_Landing.qmd
    - Notes/05-R_Projects_Connecting_with_GitHub.qmd
    - Notes/06-Quarto.qmd
    # - Notes/06_5-Week1_2.qmd
    - Notes/07-Base_R_Data_Structures_Vectors.qmd
    - Notes/08-Base_R_Data_Structures_Matrices.qmd
    - Notes/09-Base_R_Data_Structures_Data_Frames.qmd
    - Notes/10-Base_R_Data_Structures_Lists.qmd
    # - Notes/10_5-Week2_3.qmd
    - Notes/11-Control_Flow_Logicals_if_then_else.qmd
    - Notes/12-Control_Flow_Loops.qmd
    - Notes/13-Control_Flow_Vectorized_Functions.qmd
    - Notes/14-Writing_Functions.qmd
    # - Notes/14_5-Week3_4.qmd
    - Notes/15-Packages_Landing.qmd
    - Notes/16-Tidyverse_Essentials.qmd
    - Notes/17-Reading_Delimited_Data.qmd
    - Notes/18-Reading_Excel_Data.qmd
    - Notes/19-Manipulating_Data_with_dplyr.qmd
    - Notes/19_5-Week4_5.qmd
    - Notes/20-Manipulating_Data_with_tidyr.qmd
    - Notes/21-Connecting_to_Databases.qmd
    - Notes/22-SQL_Style_Joins_Landing.qmd
    - Notes/23-Querying_APIs_Landing.qmd
    - Notes/23_5-Week5_7.qmd
    - Notes/24-EDA_Concepts_Landing.qmd
    - Notes/25-Summarizing_Categorical_Variables.qmd
    - Notes/26-Barplots_ggplot_Basics_Landing.qmd
    - Notes/27-Numerical_Variable_Summaries.qmd
    - Notes/28-Numeric_Variable_Graphs_Landing.qmd
    - Notes/29-Big_Recap_Landing.qmd
    - Notes/30-Apply_Family_Landing.qmd
    - Notes/31-purrr_Landing.qmd
    - Notes/32-Advanced_Function_Writing_Landing.qmd
website:
  title: "ST 558 Data Science for Statisticians (R)"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/jbpost2/ST-558-Data-Science-for-Statisticians
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Topic 1: Data Science & R Basics"
        contents:
          - Notes/00-Welcome_to_the_Course.qmd
          - Notes/01-What_is_Data_Science.qmd
          - Notes/02-Workflows_Git_GitHub_Basics_Landing.qmd
          - Notes/03-Git_GitHub_Practice.qmd
          - Notes/04-R_Basics_Landing.qmd
          - Notes/05-R_Projects_Connecting_with_GitHub.qmd
          - Notes/06-Quarto.qmd
          - Notes/06_5-Week1_2.qmd
          - Notes/07-Base_R_Data_Structures_Vectors.qmd
          - Notes/08-Base_R_Data_Structures_Matrices.qmd
          - Notes/09-Base_R_Data_Structures_Data_Frames.qmd
          - Notes/10-Base_R_Data_Structures_Lists.qmd
          - Notes/10_5-Week2_3.qmd
          - Notes/11-Control_Flow_Logicals_if_then_else.qmd
          - Notes/12-Control_Flow_Loops.qmd
          - Notes/13-Control_Flow_Vectorized_Functions.qmd
          - Notes/14-Writing_Functions.qmd
      - section: "Topic 2: Tidyverse & EDA"
        contents:
          - Notes/14_5-Week3_4.qmd
          - Notes/15-Packages_Landing.qmd
          - Notes/16-Tidyverse_Essentials.qmd
          - Notes/17-Reading_Delimited_Data.qmd
          - Notes/18-Reading_Excel_Data.qmd
          - Notes/19-Manipulating_Data_with_dplyr.qmd
          - Notes/19_5-Week4_5.qmd
          - Notes/20-Manipulating_Data_with_tidyr.qmd
          - Notes/21-Connecting_to_Databases.qmd
          - Notes/22-SQL_Style_Joins_Landing.qmd
          - Notes/23-Querying_APIs_Landing.qmd
          - Notes/23_5-Week5_7.qmd
          - Notes/24-EDA_Concepts_Landing.qmd
          - Notes/25-Summarizing_Categorical_Variables.qmd
          - Notes/26-Barplots_ggplot_Basics_Landing.qmd
          - Notes/27-Numerical_Variable_Summaries.qmd
          - Notes/28-Numeric_Variable_Graphs_Landing.qmd
      - section: "Topic 3: Other Programming Topics"
        contents:
          - Notes/29-Big_Recap_Landing.qmd
          - Notes/30-Apply_Family_Landing.qmd
          - Notes/31-purrr_Landing.qmd
          - Notes/32-Advanced_Function_Writing_Landing.qmd
  page-navigation: true
  reader-mode: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px

callout-appearance: simple

date: today
date-format: iso


