---
title: "Week 6 Overview"
format: html
editor: visual
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

Welcome to week 6! Please see Moodle for your required videos.

This week we'll start off with a recap, and then introduce the `apply()` functions from Base R, and the (mostly) equivalent tidyverse options from the `purrr` package. We will then get into advanced function writing and querying APIs.

## Week 6 Additional Readings/Learning Materials


### `apply()` family 

[Advanced R: Chapter 9.7](https://adv-r.hadley.nz/functionals.html#base-functionals)


### `purrr`

[R for Data Science: Chapter 26.3.3](https://r4ds.hadley.nz/iteration.html#purrrmap-and-list_rbind)


### Advanced Function Writing 

[R for Data Science: Chapter 19](https://r4ds.had.co.nz/functions.html)


Upon completion of this week, students will be able to:

1. query APIs to return appropriate data (CO 2)

    a. define the term API
    b. explain the common syntax often used for APIs
    
2. have a base understanding of the common `apply()` family of functions 
    
    a. have a working understanding on how to use common apply functions 
    b. understand when to use which apply function 
    
3. have a base understanding of the `purrr` package

    a. have a working understanding on how to use common map functions 
    b. understand when it may be useful to use functions from the purrr pacakge vs Base R
    
4. Improve function writing skills 

    a. have a working understanding of how to leverage ... into our function writing 
    b. how to use stops in function writing 
    c. and more!
