---
title: "Overview"
format: html
editor: visual
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

This first week we'll mainly work on getting our workflow setup and introducing ourselves to some big ideas of the course:

-   What is data science?
-   What is `R` and how do you use it?
-   How do I create a reproducible workflow?
-   What is version control, `git`, and `github`?

## Learning Materials

After reading through the rest of this page, you should go through this week's material:

- [What is Data Science?](01-What_is_Data_Science.html)
- [Workflows & `Git`/`GitHub` Basics](02-Workflows_Git_GitHub_Basics_Landing.html)
- [`Git` & `GitHub` Practice](03-Git_GitHub_Practice.html)
- [`R` Basics](Notes/04-R_Basics_Landing.html)
- [`R` projects and Connecting with `GitHub`](05-R_projects_Connecting_with_GitHub.html)
- [`Quarto`](06-Quarto.html)

**There are also arrows at the bottom of each page to navigate to the previous page or the next page in the course!**

##  Additional Readings & Learning Materials

- Data Science Ideas

    + <a href="https://r4ds.hadley.nz/intro" target="_blank"
          rel="noopener">Introduction chapter from *`R` for Data Science*</a>
    + <a href="https://scientistcafe.com/ids/introduction#introduction"
          target="_blank" rel="noopener">Chapters 1 and 2 of the *Practitioner's Guide to Data Science*</a>
    + <a
          href="https://www.amstat.org/docs/default-source/amstat-documents/the-role-of-statistics-in-data-science-and-artificial-intelligence.pdf"
          target="_blank" rel="noopener">The role of statistics in Data Science and Artificial Intelligence</a>
    + <a href="https://en.wikipedia.org/wiki/Data_science" target="_blank"
          rel="noopener">Data Science wikipedia entry</a>

- `R` Projects and General `R` 

    + <a href="https://r4ds.hadley.nz/workflow-scripts.html#projects"
          target="_blank" rel="noopener">Chapter 6 from *R for Data Science*</a>

- `Quarto` readings:

    + <a href="https://r4ds.hadley.nz/quarto" target="_blank"
          rel="noopener">Chapters 28 & 29 from *R for Data Science*</a>

    + (Optional) <a href="https://quarto.org/" target="_blank"
          rel="noopener">Quarto documentation</a>. Specifically, the <a
          href="https://quarto.org/docs/computations/r.html" target="_blank"
          rel="noopener">using `R` portion</a>)

    + Quarto is the next generation of R Markdown. It will run most .Rmd (R markdown) files. Therefore, this <a
          href="https://bookdown.org/yihui/rmarkdown/" target="_blank"
          rel="noopener">awesome `R` Markdown book</a> is really useful.

- `Git`/`GitHub`

    + <a
          href="https://docs.github.com/en/get-started/start-your-journey/hello-world"
          target="_blank" rel="noopener">github's hello-world</a>
    + <a href="https://happygitwithr.com/install-intro" target="_blank"
          rel="noopener">Chapter 1 and readings of your choice from *Happy Git and GitHub for the useR* (formerly happygitwithR)</a>

## Week 1 Learning Objectives

Upon completion of this week, students will be able to: (CO is the corresponding course learning objective this helps build toward)

### Data Science Ideas

1. list the common duties of a data scientist (CO 5, 6)
2. create a github repository (CO 6)
3. fork, edit, and push changes to a repository (CO 6)
4. connect R Studio with github (CO 6)

    - push, pull, fork, etc. using the terminal in R or the git tab

### R Basics

1.   utilize R as a calculator (CO 1)
2.   describe the term object oriented program and the general idea of methods (CO 1)

    - store objects and change their attributes

3. describe the idea of an R package (CO 3)
4. describe the usefulness of R projects (CO 6)

    - save and load an R project
    - explain working directories, change a working directory, and specify paths to files

### Quarto

1.   list and describe the three major parts of a quarto document (YAML header, code chunks, and plain text with formatting syntax) (CO 1, 6)
    a.      outline the idea of a markdown or markup language
2.   create a quarto document (CO 1, 3, 6)
    a.      write plain text in quarto markdown syntax
    b.      create and change options for R code chunks
    c.      explain what global chunk options are and how to set them
    d.      add functionality (such as tables of contents) to outputs
3.   describe the term digital notebook (CO 6)
    a.      explain how R studio can be used as a notebook environment
    b.      run code in the markdown editor
4.   produce common types of final documents using quarto (CO 1, 3, 6)
    a.      utilize both code, menus, and shortcuts to create a document type 
    

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!