---
title: "Week 3 Overview"
format: html
toc: TRUE
editor: source
editor_options: 
  chunk_output_type: inline
---

This wraps up the content for week 2. Now we require some practice! You should head back to our <a href = "https://wolfware.ncsu.edu/" target = "_blank">Moodle site</a> to check out your homework assignment for this week.

This third week we tackle improved repeated computation through *vectorized* functions, how to write our own functions, and reading in data through the `tidyverse`. The `tidyverse` is a widely used suite of packages that all work together and allow you to read in data and do most common data manipulations.

## Week 3 (Optional) Additional Readings/Learning Materials

### Loops and Vectorized Functions<br>

- <a href="https://r4ds.hadley.nz/base-R.html" target="_blank">Chapter 27 of R 4 Data Science (27.4-27.5)</a>

### Writing Functions

- <a href="https://r4ds.hadley.nz/functions" target="_blank">Chapter 25 of R 4 Data Science</a>
- <a href = "http://adv-r.had.co.nz/Functions.html" target = "_blank">Chapter 5 of Advanced R</a>
- <a href = "https://www.r-bloggers.com/consistent-naming-conventions-in-r/" target = "_blank">Consistent naming conventions in R<a/> and <a href="https://google.github.io/styleguide/Rguide.xml" target="_blank">R's style guide</a>
- <a href="https://modern-rstats.eu/defining-your-own-functions.html#functions-that-take-functions-as-arguments-writing-your-own-higher-order-functions" target="_blank">Chapter 7 of Modern R with the tidyverse</a>

### Reading Data

- <a href = "https://r4ds.hadley.nz/data-import" target = "_blank">Chapter 7 of R 4 Data Science</a>
- <a href = "https://www.w3schools.com/sql/" target = "_blank">SQL syntax</a>


## Week 3 Learning Objectives

Upon completion of this week, students will be able to:

### Vectorized Functions

1.    program using the “apply family” of functions in R (CO 1, 3, 4)

    a.    differentiate between the apply family of functions in R including, but not limited to, mapply, sapply, lapply, apply, and replicate
    b.    manipulate R code that uses loops to instead use the proper apply function
    c.    utilize anonymous functions in calls to the apply family of functions in R

2.    recall common “vectorized” functions in R such as colMeans, rowMeans, ifelse, etc. (CO 1, 4)
3.    write their own vectorized version of a function in R (CO 1, 4)
4.    describe what an anonymous function is and how it differs from other functions (CO 1, 4)

### Writing Functions 

Note: Not all of these are covered in this week's function writing videos - we'll revisit the topic later!

1. display code from previously written functions in R (CO 1, 3)
2. describe the parts of an R function (CO 1, 4)
3. describe the difference between a prefix and an infix function (CO 1, 4)

    a. understand the order of evaluation for user created and built-in infix functions

4. write an R function that has default arguments, allows for additional arguments, and returns a well-structured named object (CO 1, 3, 4)

    a. determine appropriate uses for the stop function
    b. develop a pipeable function that acts on a data frame and one that produces side effects
    c. create a custom infix function

5. describe the way that inputs can be specified to a function (CO 1, 3)

    a. describe positional matching and predict what input values will be assigned to which function values
    b. explain lazy evaluation and give examples of where it may be important

6. use if/then/else logic to conditionally execute code
7. utilize the switch function and compare and contrast its use against if/then/else logic (CO 1, 3, 4)
8. define environments including temporary environments (CO 1)

    a. summarize the order in which R attempts to find a requested object
    b. sketch out the R environment framework and explain the idea of lexical scoping
    c. discuss the concept of local variables and local environments as compared to global variables and environments
    d. state the naming conventions for R objects


### Reading Data

1. read delimited data, SAS data files, SPSS files, and other file types into R (CO 2)

    a. describe the term delimiter
    b. read comma separated value files into R using the readr package
    c. explain how the read_ functions determine column types
    d. describe the readxl package and its functions
    e. compare and contrast tibbles and data frames

2. write a stored data set to a file using different delimiters (CO 2)


Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!
