---
title: "Week 8 Overview"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

This wraps up the content for week 7. Now we require some practice! You should head back to our <a href = "https://wolfware.ncsu.edu/" target = "_blank">Moodle site</a> to check out your assessment for this week.

This week we'll start off with a recap, and then introduce the `apply()` functions from Base R, and the (mostly) equivalent tidyverse options from the `purrr` package. We will then get into advanced function writing and querying APIs.

## Week 8 Additional Readings/Learning Materials

### `apply()` family and Function Material

Advanced R Chapters

- <a href = "http://adv-r.had.co.nz/Functions.html" target = "_blank">Advanced Function Writing</a>
- <a href = "http://adv-r.had.co.nz/Functional-programming.html" target = "_blank">Functional Programming</a>
- <a href = "http://adv-r.had.co.nz/Functionals.html" target = "_blank">Functionals</a>
- <a href = "https://r4ds.hadley.nz/rectangling" target = "_blank">Heirarchical Data</a>

<a href = "https://modern-rstats.eu/defining-your-own-functions.html" target = "_blank">Chapters 7 & 8 from Modern R with Tidyverse</a>

### `purrr`

<a href = "https://r4ds.hadley.nz/iteration.html#purrrmap-and-list_rbind" target = "_blank">R for Data Science: Chapter 26.3.3</a>

## Week 8 Learning Objectives

Upon completion of this week, students will be able to:

1. write an R function that has default arguments, allows for additional arguments, and returns a well-structured named object  

    a. determine appropriate uses for the stop function\
    b. develop a pipeable function that acts on a data frame and one that produces side effects\
    c. create a custom infix function

2. define environments including temporary environments

    a. summarize the order in which R attempts to find a requested object\
    b. sketch out the R environment framework and explain the idea of lexical scoping\
    c. discuss the concept of local variables and local environments as compared to global variables and environments\
    d. state the naming conventions for R objects

3. program using the “apply family” of functions and the purrr packing in R

    a. differentiate between the apply family of functions in R including, but not limited to, mapply, sapply, lapply, apply, and replicate\
    b. manipulate R code that uses loops to instead use the proper apply function\
    c. utilize anonymous functions in calls to the apply family of functions in R\
    d. use functions from purrr to perform data manipulations

4. describe what an anonymous function is and how it differs from other functions 

Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!