---
title: "Weeks 12 & 13 Overview"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

This wraps up the content for weeks 10 & 11. Now we require some practice! You should head back to our <a href = "https://wolfware.ncsu.edu/" target = "_blank">Moodle site</a> to check out your assessment for this week.

It's time to start modeling data!

Statistical modeling is a way to help us and others understand, interpret and make informed decisions based on data. We will also spend a lot of time on using different techniques to help us pick a best performing model from many. In addition, we will learn how to model data in the tidy framework using tidymodels. R tidymodels aims to do the same but for machine learning. It presents itself as a one-stop shop for everything ML-related, from processing data to training and evaluation models. It's an ecosystem of its own.

## Weeks 12 & 13 Additional Readings/Learning Materials

- <a href = "https://www.tidymodels.org/" target = "_blank">tidymodels homepage for you to explore</a>

- <a href = "https://www.youtube.com/watch?v=dSCFk168vmo" target = "_blank">short video on testing vs training data sets</a>

- <a href = "https://openintro-ims.netlify.app/model-mlr" target = "_blank">Linear regression with multiple predictors</a>

- <a href = "https://juliasilge.com/blog/lasso-the-office/" target = "_blank">TidyTuesday LASSO demonstration></a>

- <a href = "https://openintro-ims.netlify.app/model-logistic" target = "_blank">Logistic Regression:9.1-9.3</a>

- <a href = "https://www.nature.com/articles/nmeth.4370" target = "_blank">Regression and Classification Trees article</a>

- <a href = "https://www.youtube.com/watch?v=jbkSRLYSojo&t=121s" target = "_blank">Communicating a story with data (Hans Rosling)</a>

<ul>
  <li><a href="https://www.statlearning.com/" target="_blank"
        rel="noopener">ISLR book</a>: Read section (Big picture ideas) 2.1, 2.2,
      (Basic regression) 3.1, 3.2, 3.3, (Basic logistic regression) 4.1, 4.2, 4.3,
      (CV) 5.1, (Regularized models) 6.2</li>
    <li id="yui_3_17_2_1_1720810704083_4783">Chapters 4-15 of the <a
        href="https://www.tmwr.org/performance" target="_blank"
        rel="noopener">tidymodels</a> (especially chapter 9)</li>
    <li>Google's open course materials has information about these models, loss
      functions, metrics, etc: <a
        href="https://developers.google.com/machine-learning/crash-course/classification/video-lecture"
        target="_blank"
        rel="noopener">https://developers.google.com/machine-learning/crash-course/classification/video-lecture</a>
    </li>
    <li>(Optional)  <a
        href="https://web.stanford.edu/~hastie/ElemStatLearn/download.html"
        target="_blank" rel="noopener">Elements of Statistical Learning</a> (see
      table of contents - similar readings, just more advanced)</li>
    <li>(Optional) <a href="https://www.tidyverse.org/tags/tidymodels/"
        target="_blank" rel="noopener">tidymodels blog</a></li>
</ul>


## Learning Objectives

Upon completion of these two weeks, students will be able to:

### Linear Regression Models

1.    describe the idea of supervised learning and compare and contrast it with unsupervised learning

2.    conduct an exploratory data analysis

3.    utilize the lm() function along with formula notation in R to fit linear models

    a.    lay out the basic simple linear regression model and explain how the models are commonly fit to data in R\
    b.    access elements of a fitted lm object\
    c.    find predictions using a simple linear regression model and provide standard errors, confidence bounds, and prediction bounds\
    d.    utilize the lm() function and formula notation in R to fit multiple linear regression models and polynomial regression models\
    e.    define the terms polynomial regression and multiple linear regression
    
4.    explain the concept of how a multiple linear regression model is usually fit and what the effect of adding in more predictor terms is on the model

    a.    find predictions using a multiple linear regression model and provide standard errors, confidence bounds, and prediction bounds\
    b.    explain how adding categorical predictors changes a linear model\
    c.    interpret the coefficients of a general linear model and use it for prediction purposes

5.    describe common methods used to select between models

6.    define prediction error, training sets, and test sets

    a.    explain why splitting data into training and tests sets is needed\
    b.    discuss the nature/behavior of predicting on your training set vs predicting on a test set

7.    use a linear regression or logistic regression model to perform classification

    a.    describe the type of scenario where logistic regression may be a reasonable modeling choose\
    b.    define the logistic regression model and state its advantages for modeling binary outcomes\
    c.    create visuals to help explore binary outcome data appropriate for logistic regression\
    d.    interpret model coefficients from a logistic regression model\
    e.    fit logistic regression models in R and use them for prediction purposes (probability, link, odds, or classification)\
    k.    predict for new data using a logistic regression model

### Nonlinear & Ensemble Models

1.    fit and interpret regression and classification trees in R

    a.    describe the terms regression tree and classification tree\
    b.    explain the difference between using a tree based method and using a linear method\
    c.    provide visuals of tree fits in R\
    d.    predict using a tree fit in R\
    e.    roughly break down the steps used in fitting a regression tree\
    f.    explain the term "greedy" algorithm\
    g.    prune a fitted tree and describe why this is often needed\
    h.    compare and contrast the fitting and pruning of regression trees vs classification trees\
    i.    describe the pros and cons of using tree based methods

2.    select a final model using cross validation

3.    fit and interpret bagged tree and random forests models in R

    a.    explain the term ensemble methods and how it can be applied to tree based methods\
    b.    describe why ensemble methods can often improve predictions\
    c.    give the cons of using ensemble methods\
    d.    investigate variable importance measures for ensemble trees\
    e.    Outline the bagging algorithm\
    f.    outline the random forest algorithm


### Tidymodels Framework and Model Fitting

1. Use the tidymodels framework to fit and evaluate models

    a.   describe how recipes work and why they are useful when fitting models\
    b.   outline the purpose of how tidymodels creates models by specifying the model type and engine\
    c.    utilize workflows for fitting models

2. Compare and contrast using a training/test set, using cross-validation only, and using both the training set with CV and a test set

3. Describe and explain the pros and cons of commonly used model metrics

4. Explain the difference between a loss function and a model metric 


Use the table of contents on the left or the arrows at the bottom of this page to navigate to the next learning material!
